### PR TITLE
Style/gui refinements

### LINKED ISSUE #83: Various minor GUI refinements
**Is your feature request related to a problem? Please describe.**
Not really a problem. The UI as-is is generally inoffensive, and straightforward to navigate, but can perhaps be afforded some more flair to give it a little more dimension.

**Describe the solution you'd like**
I’d quite like to dig around the pages and make some small tweaks to lift the design system a little. No precise designs in mind at this point, but obviously this would be reviewed (and potentially rejected!).

**Describe alternatives you've considered**
Just sticking with the current GUI, I guess. Which, I mean, really isn’t so bad, but my point above stands.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by jaskfla**
### Changes

Various UI refinements and minor tidy-ups. Most notably:

- Using slightly cool grey instead of pure grey
- Animating hover effects (generally colours and shadows)
- Removed a few redundant HTML tags in components to simplify DOM structure
- Edited _About_ and _Contact_ page prose for conciseness.

### Tests applied

Manual testing.

### Issue ticket number(s)

Closes #83 

### Checklist

- [x] Documented
- [x] Linting tests successful
- [x] merge updated prod branch into development branch

### CODE REVIEW

**Comment by jaskfla** [comment]
There’s a force push because I accidentally synced the `main` branch to the features branch on my fork, which I fixed by syncing to `main` of my fork and then merging into the feature branch.

**Review by JC4github — CHANGES_REQUESTED** [review]
- can you make the logout button colour match the rest of the UI 
- can you add hover effects to buttons on home page

The rest of the new style looks very good!

**Comment by jaskfla** [comment]
Oops, good catch re logout button—thanks!

And good idea about the home page hover effects. I’ll get that sorted and update the branch.

**Comment by jaskfla** [comment]
Those two issues should be resolved now—thanks for catching them

**Review by cste303 — CHANGES_REQUESTED** [review]
Looks good I like the new style. Just one thing on the degree planner page the search and save buttons are different colours. If you could fix that up will be happy to approve.

**Comment by jaskfla** [comment]
Fixed!

**Review by cste303 — APPROVED** [review]
Thanks for fixing up those colours LGTM.

**Review by JC4github — APPROVED** [review]
Looks great!

**Pull request merged**
